# Generated by Django 3.1.4 on 2020-12-11 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_somemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SomeModel',
        ),
    ]
